[package]
name = "kite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
clap = {version="3.2.17", features=["derive"]}
syntect = "5.0.0"
unicode-segmentation = "1.9.0"